class STOCK_DATA(TypedDict):
    股票代碼: str
    總委買筆數: str
    總委賣筆數: str
    相關股票: str
    前一日收盤價: str
    跌停價: str
    成交流水(千股): str
    委買價: str
    委賣價: str
    暫無用途: str
    日期（西元年月日）: str
    資料鍵值（交易所_代碼_日期）: str
    五檔賣出價格（_分隔）: str
    五檔買入價格（_分隔）: str
    股票代碼（純數字）: str
    時間（最後更新時間）: str
    股票代碼（完整）: str
    時間戳（毫秒）: str
    最終撮合時間: str
    五檔買入量（_分隔）: str
    五檔賣出量（_分隔）: str
    總委買張數: str
    今日最高價: str
    最小跳動單位: str
    單位張數: str
    成交價（最後成交）: str
    今日最低價: str
    股票簡稱: str
    開盤價: str
    交易所: str
    成交筆數: str
    最後成交時間: str
    漲停價: str
    成交張數: str
    股票全名: str
    昨日收盤價: str
    目前成交價: str
    每日交易資料:
